todo/task/urls.py
from django.urls import path
from .views import (
    TaskCreateView, TaskListView, TaskTimeoutListView,
    TaskImportantListView, TaskNormalListView, TaskMinorListView,
    TaskUpdateView, TaskDeleteView)

app_name = 'task'
urlpatterns = [
    path('create/', TaskCreateView.as_view(), name='create'),
    path('complete/<int:id>/', TaskUpdateView.as_view(), name='complete'),
    path('list/', TaskListView.as_view(), name='list'),
    path('timeout/', TaskTimeoutListView.as_view(), name='timeout'),
    path('important/', TaskImportantListView.as_view(), name='important'),
    path('normal/', TaskNormalListView.as_view(), name='normal'),
    path('minor/', TaskMinorListView.as_view(), name='minor'),
    path('delete/<int:id>/', TaskDeleteView.as_view(), name='delete'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from task.views import SignupView, LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task/', include('task.urls')),
    path('accounts/signup/', SignupView.as_view(), name='signup'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

todo/task/models.py
from datetime import date, datetime

from django.conf import settings
from django.db import models
from django.utils.timezone import now

PRIORITY = (
    ('1', '중요'),
    ('2', '보통'),
    ('3', '사소'),
)


class Todo(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    note = models.TextField(blank=True)
    deadline = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=1, choices=PRIORITY, default='2')

    created_date = models.DateTimeField(default=now)


    def __str__(self):
        return self.title

    def date_now(self):
        return date.today()

    def over_date(self):
        if date.today() > self.deadline:
            return True

    class Meta:
        ordering = ["priority", 'deadline']

todo/task/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect

from .models import Todo, PRIORITY


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'note', 'deadline', 'priority']

    title = forms.CharField(
        label='할 일',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '무엇을 할까',
                'id': 'title',
            }
        )
    )

    note = forms.CharField(
        label='자세한 내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '자세한 내용',
            }
        )
    )

    deadline = forms.DateTimeField(
        label='언제까지',
        widget=forms.DateTimeInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    priority = forms.ChoiceField(
        choices=PRIORITY,
        label="중요도",
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )


class CreateUserForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        label='ID',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': ''
            }
        )
    )

    password1 = forms.CharField(
        required=True,
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '문자와 숫자를 포함해 8자리 이상 입력'
            }
        )
    )

    password2 = forms.CharField(
        required=True,
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '같은 비밀번호를 다시 입력'
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

todo/task/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import ListView, CreateView, FormView, RedirectView, UpdateView

from .models import Todo
from .forms import TodoForm, CreateUserForm


class TodoCountMixin(object):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list'] = Todo.objects.filter(author=self.request.user).count()
        context['overtime'] = Todo.objects.filter(author=self.request.user, deadline__lt=datetime.now()).count()
        context['important'] = Todo.objects.filter(author=self.request.user, priority='1').count()
        context['normal'] = Todo.objects.filter(author=self.request.user, priority='2').count()
        context['minor'] = Todo.objects.filter(author=self.request.user, priority='3').count()
        return context


class SignupView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('task:list')


class LoginView(FormView):
    template_name = 'registration/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('task:list')

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)


class LogoutView(RedirectView):
    url = ''
    pattern_name = 'task:list'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class TaskCreateView(TodoCountMixin, CreateView):
    template_name = 'task/todo_create.html'
    form_class = TodoForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TaskCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('task:list')


class TaskListView(TodoCountMixin, ListView):
    template_name = 'task/todo_list.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TaskListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Todo.objects.filter(author=self.request.user)


class TaskTimeoutListView(TodoCountMixin, ListView):
    template_name = 'task/todo_list.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TaskTimeoutListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Todo.objects.filter(author=self.request.user, deadline__lt=datetime.now())


class TaskImportantListView(TodoCountMixin, ListView):
    template_name = 'task/todo_list.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TaskImportantListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Todo.objects.filter(author=self.request.user, priority='1')


class TaskNormalListView(TodoCountMixin, ListView):
    template_name = 'task/todo_list.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TaskNormalListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Todo.objects.filter(author=self.request.user, priority='2')


class TaskMinorListView(TodoCountMixin, ListView):
    template_name = 'task/todo_list.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TaskMinorListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Todo.objects.filter(author=self.request.user, priority='3')


class TaskUpdateView(View):
    def dispatch(self, request, id):
        task = Todo.objects.get(id=id)
        task.completed = not task.completed
        task.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class TaskDeleteView(View):

    def dispatch(self, request, id):
        Todo.objects.filter(id=id).delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

todo/templates/task/todo_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data" class="">{% csrf_token %}
	{% for field in form %}
	<div class="form-group row">
		<label class="col-sm-2 col-form-label" for="{{ field.name }}">{{ field.label }}</label>
		<div class="col-sm-10">
			{{ field }}
		</div>
	</div>
	{% endfor %}
	<div class="form-group row">
		<div class="col-sm-10">
			<button type="submit" class="btn btn-default">Add Todo</button>
		</div>
	</div>
</form>

{% endblock %}

todo/templates/task/todo_list.html
{% extends 'base.html' %}

{% block content %}
<div class="card" style="margin-bottom: 10px;">
    <a class="btn btn-primary" href="{% url 'task:create' %}" role="button">+</a>
</div>

{% for obj in object_list %}
<div class="card" style="margin-bottom: 10px;">
    <div class="card-body">
        <h5 class="card-title">
            {% if obj.priority == '1' %}
            <span class="badge badge-warning">{{ obj.get_priority_display }}</span>
            {% elif obj.priority == '2' %}
            <span class="badge badge-primary">{{ obj.get_priority_display }}</span>
            {% else %}
            <span class="badge badge-light">{{ obj.get_priority_display }}</span>
            {% endif %}
            : {{ obj.title }}</h5>
        {% if obj.date_now|date:"Y M d" > obj.deadline|date:"Y M d" %}
        <h6 class="card-subtitle mb-2 text-muted">
            <del>{{ obj.deadline|date:"Y M d D" }}</del>
            지남
        </h6>
        {% else %}
        <h6 class="card-subtitle mb-2 text-muted">{{ obj.deadline|date:"Y M d D" }}까지</h6>
        {% endif %}
        <p class="card-text">{{ obj.note }}</p>

        {% if obj.completed == False %}
            <a href="{% url 'task:complete' obj.id %}" class="btn btn-outline-secondary btn-sm" role="button" aria-pressed="true" style="width: 140px;">{{ obj.completed|yesno:"완료, 미완료" }}</a>
        {% else %}
            <a href="{% url 'task:complete' obj.id %}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true" style="width: 140px;">{{ obj.completed|yesno:"완료, 미완료" }}</a>
        {% endif %}
        <a href="{% url 'task:delete' obj.id %}" class="btn btn-outline-danger btn-sm" role="button"
               aria-pressed="true" style="width: 140px;">Delete</a>
    </div>
</div>
{% endfor %}

{% endblock %}