todo/task/urls.py
from django.urls import path
from .views import (
    TaskCreateView, TaskListView, TaskTimeoutListView,
    TaskImportantListView, TaskNormalListView, TaskMinorListView,
    TaskUpdateView, TaskDeleteView)

app_name = 'task'
urlpatterns = [
    path('create/', TaskCreateView.as_view(), name='create'),
    path('complete/<int:id>/', TaskUpdateView.as_view(), name='complete'),
    path('list/', TaskListView.as_view(), name='list'),
    path('timeout/', TaskTimeoutListView.as_view(), name='timeout'),
    path('important/', TaskImportantListView.as_view(), name='important'),
    path('normal/', TaskNormalListView.as_view(), name='normal'),
    path('minor/', TaskMinorListView.as_view(), name='minor'),
    path('delete/<int:id>/', TaskDeleteView.as_view(), name='delete'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from task.views import SignupView, LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task/', include('task.urls')),
    path('accounts/signup/', SignupView.as_view(), name='signup'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

todo/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{% static 'css/custom.css' %}">-->
</head>
</html>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-bottom: 10px;">
    <a class="navbar-brand" href="">Todo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'task:list' %}"> Home <span
                        class="badge badge-secondary">{{ list }}</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'task:timeout' %}">
                    Timeout
                    <span class="badge badge-danger">
                        {{ overtime }}
                    </span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Priority
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'task:important' %}">중요 <span class="badge badge-warning">{{ important }}</span></a>
                    <a class="dropdown-item" href="{% url 'task:normal' %}">보통 <span class="badge badge-primary">{{ normal }}</span></a>
                    <a class="dropdown-item" href="{% url 'task:minor' %}">사소 <span class="badge badge-light">{{ minor }}</span></a>
                </div>
            </li>

        </ul>
        <ul class="navbar-nav navbar-right">
            <li class="nav-item navbar-text" style="margin-right: 10px;">{{ user.username }}님</li>
            <li class="nav-item"><a class="nav-link btn btn-secondary btn-sm" role="button" href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
</nav>
<div class="container mx-auto" style="width: 800px;">
    {% block content %}

    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
</body>